// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        CData/*0:0*/ top__DOT____Vcellinp__ebreak_box__is_ebreak;
        VL_IN8(reset,0,0);
        VL_OUT8(io_halt_ret,0,0);
        VL_OUT8(io_non_inst,0,0);
        VL_OUT8(io_difftest_valid,0,0);
        CData/*0:0*/ top__DOT__cpu__DOT___slave_selector_io_slave_in_AWREADY;
        CData/*0:0*/ top__DOT__cpu__DOT___slave_selector_io_slave_in_BVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___slave_selector_io_slave_in_ARREADY;
        CData/*0:0*/ top__DOT__cpu__DOT___slave_selector_io_slave_in_RVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___slave_selector_io_slave_m_AWVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_arbiter_io_i_master_ARREADY;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_arbiter_io_i_master_RVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_arbiter_io_m_master_BVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_arbiter_io_m_master_RVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_arbiter_io_slave_ARVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_arbiter_io_is_inst;
        CData/*0:0*/ top__DOT__cpu__DOT___DSRAM_io_M_bus_ARREADY;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_mem_master_io_M_bus_AWVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_mem_master_io_M_bus_ARVALID;
        CData/*0:0*/ top__DOT__cpu__DOT___axi_ifu_master_io_I_bus_RREADY;
        CData/*0:0*/ top__DOT__cpu__DOT___exu_io_branch_bits_is_branch_taken;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_in_ready;
        CData/*3:0*/ top__DOT__cpu__DOT___idu_io_out_bits_alu_op;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_csrrw;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_csrrs;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_lw;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_sw;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_lb;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_sb;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_lh;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_sh;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_lbu;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_lhu;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_beq;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_bne;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_blt;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_bltu;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_bge;
        CData/*0:0*/ top__DOT__cpu__DOT___idu_io_out_bits_is_bgeu;
        CData/*0:0*/ top__DOT__cpu__DOT___ifu_io_inst_req_valid;
        CData/*0:0*/ top__DOT__cpu__DOT___ifu_io_inst_resp_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__busy;
        CData/*0:0*/ top__DOT__cpu__DOT__ifu__DOT__state;
        CData/*0:0*/ top__DOT__cpu__DOT__ifu__DOT__out_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__ifu__DOT__io_flush_0;
        CData/*0:0*/ top__DOT__cpu__DOT__ifu__DOT___GEN;
        CData/*0:0*/ top__DOT__cpu__DOT__ifu__DOT___GEN_0;
        CData/*0:0*/ top__DOT__cpu__DOT__ifu__DOT___GEN_1;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT__state;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT__is_load;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT__is_srai;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT__is_srli;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT__is_slli;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT__is_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT__is_store;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT____VdfgRegularize_hdcfcc17d_1_5;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT____VdfgRegularize_hdcfcc17d_1_10;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT____VdfgRegularize_hdcfcc17d_1_11;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT____VdfgRegularize_hdcfcc17d_1_12;
        CData/*0:0*/ top__DOT__cpu__DOT__idu__DOT____VdfgRegularize_hdcfcc17d_1_13;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__state;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__out_valid;
    };
    struct {
        CData/*3:0*/ top__DOT__cpu__DOT__exu__DOT__alu_op;
        CData/*4:0*/ top__DOT__cpu__DOT__exu__DOT__rd_addr;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__rd_en;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__csr_wen;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_csrrw;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_csrrs;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_lw;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_lbu;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_lh;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_lhu;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_lb;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_sw;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_sb;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_sh;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_ecall;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_mret;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_beq;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_bne;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_blt;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_bltu;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_bge;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT__is_bgeu;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT___GEN;
        CData/*0:0*/ top__DOT__cpu__DOT__exu__DOT___GEN_0;
        CData/*4:0*/ top__DOT__cpu__DOT__mem__DOT__rd_addr;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__rd_en;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__csr_wen;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_csrrw;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_csrrs;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_lw;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_lbu;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_lh;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_lhu;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_lb;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_sw;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_sb;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_sh;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__is_load;
        CData/*1:0*/ top__DOT__cpu__DOT__mem__DOT__state;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__out_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT__io_mem_req_valid_0;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT___GEN_1;
        CData/*7:0*/ top__DOT__cpu__DOT__mem__DOT__casez_tmp;
        CData/*0:0*/ top__DOT__cpu__DOT__mem__DOT___GEN_2;
        CData/*1:0*/ top__DOT__cpu__DOT__mem__DOT__casez_tmp_0;
        CData/*4:0*/ top__DOT__cpu__DOT__wb__DOT__rd_addr;
        CData/*0:0*/ top__DOT__cpu__DOT__wb__DOT__rd_en;
        CData/*0:0*/ top__DOT__cpu__DOT__wb__DOT__is_load;
        CData/*0:0*/ top__DOT__cpu__DOT__wb__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__wb__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__wb__DOT__csr_wen;
        CData/*0:0*/ top__DOT__cpu__DOT__wb__DOT__is_csrrw;
        CData/*0:0*/ top__DOT__cpu__DOT__wb__DOT__is_csrrs;
        CData/*0:0*/ top__DOT__cpu__DOT__wb__DOT___GEN;
        CData/*1:0*/ top__DOT__cpu__DOT__wb__DOT__state;
        CData/*1:0*/ top__DOT__cpu__DOT__wb__DOT__casez_tmp;
        CData/*0:0*/ top__DOT__cpu__DOT__regfile__DOT___GEN;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_ifu_master__DOT__pending;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_ifu_master__DOT__killPending;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_ifu_master__DOT__io_I_bus_ARVALID_0;
    };
    struct {
        CData/*0:0*/ top__DOT__cpu__DOT__axi_ifu_master__DOT__r_fire;
        CData/*1:0*/ top__DOT__cpu__DOT__axi_mem_master__DOT__state;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_mem_master__DOT___GEN;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_mem_master__DOT___GEN_0;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_mem_master__DOT__io_mem_req_ready_0;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_mem_master__DOT___GEN_2;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_mem_master__DOT__io_M_bus_RREADY_0;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_mem_master__DOT___GEN_3;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_mem_master__DOT__io_M_bus_BREADY_0;
        CData/*1:0*/ top__DOT__cpu__DOT__DSRAM__DOT__state;
        CData/*0:0*/ top__DOT__cpu__DOT__DSRAM__DOT__idle;
        CData/*0:0*/ top__DOT__cpu__DOT__DSRAM__DOT__io_M_bus_WREADY_0;
        CData/*0:0*/ top__DOT__cpu__DOT__DSRAM__DOT__ar_fire;
        CData/*0:0*/ top__DOT__cpu__DOT__DSRAM__DOT___GEN;
        CData/*0:0*/ top__DOT__cpu__DOT__DSRAM__DOT___GEN_0;
        CData/*0:0*/ top__DOT__cpu__DOT__DSRAM__DOT__io_M_bus_RVALID_0;
        CData/*0:0*/ top__DOT__cpu__DOT__DSRAM__DOT___GEN_1;
        CData/*0:0*/ top__DOT__cpu__DOT__DSRAM__DOT__io_M_bus_BVALID_0;
        CData/*0:0*/ top__DOT__cpu__DOT__ISRAM__DOT___imem_inst_valid;
        CData/*1:0*/ top__DOT__cpu__DOT__ISRAM__DOT__state;
        CData/*0:0*/ top__DOT__cpu__DOT__ISRAM__DOT__io_I_bus_ARREADY_0;
        CData/*0:0*/ top__DOT__cpu__DOT__ISRAM__DOT___GEN;
        CData/*0:0*/ top__DOT__cpu__DOT__ISRAM__DOT___GEN_0;
        CData/*0:0*/ top__DOT__cpu__DOT__ISRAM__DOT___GEN_1;
        CData/*0:0*/ top__DOT__cpu__DOT__ISRAM__DOT__io_I_bus_RVALID_0;
        CData/*0:0*/ top__DOT__cpu__DOT__ISRAM__DOT__imem__DOT__pc_valid_r;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT__busy;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT__using_ifu;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT__is_write;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT__pick_ifu;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT__awvalid;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT___GEN;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT___GEN_1;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT__arvalid;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT__io_slave_BREADY_0;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT___GEN_2;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT__io_slave_RREADY_0;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT___GEN_3;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT___GEN_4;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT___GEN_5;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT____VdfgRegularize_h24e09026_0_6;
        CData/*0:0*/ top__DOT__cpu__DOT__axi_arbiter__DOT____VdfgRegularize_h24e09026_0_7;
        CData/*0:0*/ top__DOT__cpu__DOT__slave_selector__DOT___GEN;
        CData/*0:0*/ top__DOT__cpu__DOT__slave_selector__DOT___GEN_0;
        CData/*0:0*/ top__DOT__cpu__DOT__slave_selector__DOT____VdfgRegularize_hdf3ce10e_0_1;
        CData/*0:0*/ top__DOT__cpu__DOT__slave_selector__DOT____VdfgRegularize_hdf3ce10e_0_2;
        CData/*0:0*/ top__DOT__cpu__DOT__slave_selector__DOT____VdfgRegularize_hdf3ce10e_0_3;
        CData/*0:0*/ __VdfgRegularize_hd87f99a1_2_0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__top__DOT____Vcellinp__ebreak_box__is_ebreak__0;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ top__DOT__cpu__DOT___idu_io_csr_raddr;
        SData/*11:0*/ top__DOT__cpu__DOT__exu__DOT__csr_waddr;
        SData/*11:0*/ top__DOT__cpu__DOT__mem__DOT__csr_waddr;
        SData/*15:0*/ top__DOT__cpu__DOT__mem__DOT__sel_half;
        SData/*11:0*/ top__DOT__cpu__DOT__wb__DOT__csr_waddr;
        VL_OUT(io_pc,31,0);
        VL_OUT(io_inst,31,0);
        VL_OUT(io_gpr_0,31,0);
        VL_OUT(io_gpr_1,31,0);
        VL_OUT(io_gpr_2,31,0);
        VL_OUT(io_gpr_3,31,0);
        VL_OUT(io_gpr_4,31,0);
    };
    struct {
        VL_OUT(io_gpr_5,31,0);
        VL_OUT(io_gpr_6,31,0);
        VL_OUT(io_gpr_7,31,0);
        VL_OUT(io_gpr_8,31,0);
        VL_OUT(io_gpr_9,31,0);
        VL_OUT(io_gpr_10,31,0);
        VL_OUT(io_gpr_11,31,0);
        VL_OUT(io_gpr_12,31,0);
        VL_OUT(io_gpr_13,31,0);
        VL_OUT(io_gpr_14,31,0);
        VL_OUT(io_gpr_15,31,0);
        VL_OUT(io_gpr_16,31,0);
        VL_OUT(io_gpr_17,31,0);
        VL_OUT(io_gpr_18,31,0);
        VL_OUT(io_gpr_19,31,0);
        VL_OUT(io_gpr_20,31,0);
        VL_OUT(io_gpr_21,31,0);
        VL_OUT(io_gpr_22,31,0);
        VL_OUT(io_gpr_23,31,0);
        VL_OUT(io_gpr_24,31,0);
        VL_OUT(io_gpr_25,31,0);
        VL_OUT(io_gpr_26,31,0);
        VL_OUT(io_gpr_27,31,0);
        VL_OUT(io_gpr_28,31,0);
        VL_OUT(io_gpr_29,31,0);
        VL_OUT(io_gpr_30,31,0);
        VL_OUT(io_gpr_31,31,0);
        IData/*31:0*/ top__DOT__cpu__DOT___slave_selector_io_slave_in_RDATA;
        IData/*31:0*/ top__DOT__cpu__DOT___slave_selector_io_slave_i_ARADDR;
        IData/*31:0*/ top__DOT__cpu__DOT___axi_arbiter_io_slave_ARADDR;
        IData/*31:0*/ top__DOT__cpu__DOT___axi_mem_master_io_mem_resp_bits_rdata;
        IData/*31:0*/ top__DOT__cpu__DOT___regfile_io_rs1_data;
        IData/*31:0*/ top__DOT__cpu__DOT___regfile_io_rs2_data;
        IData/*31:0*/ top__DOT__cpu__DOT___wb_io_rd_data;
        IData/*31:0*/ top__DOT__cpu__DOT___exu_io_branch_bits_pc_branch;
        IData/*31:0*/ top__DOT__cpu__DOT___idu_io_out_bits_alu_b;
        IData/*31:0*/ top__DOT__cpu__DOT__ifu__DOT__pc;
        IData/*31:0*/ top__DOT__cpu__DOT__ifu__DOT__pc_reg;
        IData/*31:0*/ top__DOT__cpu__DOT__ifu__DOT__inst_reg;
        IData/*31:0*/ top__DOT__cpu__DOT__ifu__DOT___pc_T;
        IData/*31:0*/ top__DOT__cpu__DOT__idu__DOT__inst;
        IData/*31:0*/ top__DOT__cpu__DOT__idu__DOT__pc;
        IData/*31:0*/ top__DOT__cpu__DOT__idu__DOT__imm_i;
        IData/*31:0*/ top__DOT__cpu__DOT__exu__DOT__alu_a;
        IData/*31:0*/ top__DOT__cpu__DOT__exu__DOT__alu_b;
        IData/*31:0*/ top__DOT__cpu__DOT__exu__DOT__rs1_data;
        IData/*31:0*/ top__DOT__cpu__DOT__exu__DOT__rs2_data;
        IData/*31:0*/ top__DOT__cpu__DOT__exu__DOT__csr_rdata;
        IData/*31:0*/ top__DOT__cpu__DOT__exu__DOT__pc;
        IData/*31:0*/ top__DOT__cpu__DOT__exu__DOT__csr_wdata;
        IData/*31:0*/ top__DOT__cpu__DOT__exu__DOT__alu__DOT__casez_tmp;
        IData/*31:0*/ top__DOT__cpu__DOT__mem__DOT__pc;
        IData/*31:0*/ top__DOT__cpu__DOT__mem__DOT__alu_result;
        IData/*31:0*/ top__DOT__cpu__DOT__mem__DOT__rs2_data;
        IData/*31:0*/ top__DOT__cpu__DOT__mem__DOT__csr_wdata;
        IData/*31:0*/ top__DOT__cpu__DOT__mem__DOT__csr_rdata;
        IData/*31:0*/ top__DOT__cpu__DOT__mem__DOT__mem_data;
        IData/*31:0*/ top__DOT__cpu__DOT__wb__DOT__pc;
        IData/*31:0*/ top__DOT__cpu__DOT__wb__DOT__alu_result;
        IData/*31:0*/ top__DOT__cpu__DOT__wb__DOT__mem_data;
        IData/*31:0*/ top__DOT__cpu__DOT__wb__DOT__csr_wdata;
        IData/*31:0*/ top__DOT__cpu__DOT__wb__DOT__csr_rdata;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_0;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_1;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_2;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_3;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_4;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_5;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_6;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_7;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_8;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_9;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_10;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_11;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_12;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_13;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_14;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_15;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_16;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_17;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_18;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_19;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_20;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_21;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_22;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_23;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_24;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_25;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_26;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_27;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_28;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_29;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_30;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__regs_31;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__casez_tmp;
        IData/*31:0*/ top__DOT__cpu__DOT__regfile__DOT__casez_tmp_0;
        IData/*31:0*/ top__DOT__cpu__DOT__DSRAM__DOT___mem_blackbox_rdata;
        IData/*31:0*/ top__DOT__cpu__DOT__DSRAM__DOT__rdata_reg;
        IData/*31:0*/ top__DOT__cpu__DOT__ISRAM__DOT___imem_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__ISRAM__DOT__pc_lat;
        IData/*31:0*/ top__DOT__cpu__DOT__ISRAM__DOT__mem_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__ISRAM__DOT__imem__DOT__pc_r;
        IData/*31:0*/ top__DOT__cpu__DOT__slave_selector__DOT__addr;
        IData/*31:0*/ top__DOT__cpu__DOT__csr__DOT__mtvec;
        IData/*31:0*/ top__DOT__cpu__DOT__csr__DOT__mepc;
        IData/*31:0*/ top__DOT__cpu__DOT__csr__DOT__mcause;
        IData/*31:0*/ top__DOT__cpu__DOT__csr__DOT__mstatus;
        IData/*31:0*/ __Vfunc_top__DOT__cpu__DOT__DSRAM__DOT__mem_blackbox__DOT__pmem_read__0__Vfuncout;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*0:0*/, 2> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
